version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: silentcanary-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - REDIS_URL=redis://redis:6379/0
      - AWS_DEFAULT_REGION=ca-central-1
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    depends_on:
      - redis
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout 120 app:app

  worker:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: silentcanary-worker
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - REDIS_URL=redis://redis:6379/0
      - AWS_DEFAULT_REGION=ca-central-1
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    command: python worker.py

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: silentcanary-scheduler
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - REDIS_URL=redis://redis:6379/0
      - AWS_DEFAULT_REGION=ca-central-1
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    command: python -c "import time; print('Scheduler placeholder - will implement later')"

  redis:
    image: redis:7-alpine
    container_name: silentcanary-redis
    restart: unless-stopped
    # Remove external port mapping - only accessible from within Docker network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  nginx:
    image: nginx:alpine
    container_name: silentcanary-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - app

volumes:
  redis_data: