apiVersion: apps/v1
kind: Deployment
metadata:
  name: silentcanary-app
  namespace: silentcanary
  labels:
    app: silentcanary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: silentcanary
  template:
    metadata:
      labels:
        app: silentcanary
    spec:
      containers:
      - name: silentcanary
        image: 251132308531.dkr.ecr.ca-central-1.amazonaws.com/silentcanary:timezone-fix-329c606
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: AWS_DEFAULT_REGION
          value: "ca-central-1"
        - name: DYNAMODB_LOCAL
          value: ""
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: silentcanary-secrets
              key: sendgrid-api-key
        - name: SENDGRID_DEFAULT_SENDER
          valueFrom:
            secretKeyRef:
              name: silentcanary-secrets
              key: sendgrid-default-sender
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: silentcanary-secrets
              key: sendgrid-api-key
        - name: MAIL_DEFAULT_SENDER
          valueFrom:
            secretKeyRef:
              name: silentcanary-secrets
              key: sendgrid-default-sender
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: silentcanary-secrets
              key: flask-secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 20
      # Use IAM roles for service accounts (IRSA) instead of embedding credentials
      serviceAccountName: silentcanary-service-account
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: silentcanary-service
  namespace: silentcanary
  labels:
    app: silentcanary
spec:
  selector:
    app: silentcanary
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP