name: Test Canary Failure Detection

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H 35.182.6.75 >> ~/.ssh/known_hosts

    - name: Run canary failure detection test
      run: |
        echo "🧪 Testing canary failure detection system..."
        ssh -i ~/.ssh/id_rsa ubuntu@35.182.6.75 'cd /opt/silentcanary && docker exec silentcanary-worker python3 test_canary_failure_detection.py'
